"""
Service for managing reports generated by agents
"""

from typing import List, Optional, Dict, Any
from sqlalchemy.orm import Session

from app.models.query import Query
from app.models.report import Report
from app.schemas.report import ReportResponse, RiskAnalysisResponse, ActionPlanResponse


class ReportService:
    """Service for managing reports"""
    
    @staticmethod
    def create_report(
        db: Session,
        query_id: int,
        report_type: str,
        json_report: Dict[str, Any],
        confidence_score: Optional[float] = None,
        processing_time: Optional[float] = None,
        agent_version: Optional[str] = None
    ) -> Report:
        """
        Create a new report
        
        Args:
            db: Database session
            query_id: Query ID
            report_type: Type of report (risk_analysis or action_plan)
            json_report: Complete JSON report from agent
            confidence_score: Optional confidence score
            processing_time: Optional processing time in seconds
            agent_version: Optional agent version
            
        Returns:
            Report: Created report
        """
        db_report = Report(
            query_id=query_id,
            report_type=report_type,
            json_report=json_report,
            confidence_score=confidence_score,
            processing_time=processing_time,
            agent_version=agent_version
        )
        
        db.add(db_report)
        db.commit()
        db.refresh(db_report)
        
        return db_report
    
    @staticmethod
    def get_report(db: Session, report_id: int) -> Optional[Report]:
        """
        Get a report by ID
        
        Args:
            db: Database session
            report_id: Report ID
            
        Returns:
            Report: Found report or None
        """
        return db.query(Report).filter(Report.id == report_id).first()
    
    @staticmethod
    def get_query_reports(db: Session, query_id: int) -> List[Report]:
        """
        Get all reports for a query
        
        Args:
            db: Database session
            query_id: Query ID
            
        Returns:
            List[Report]: List of reports
        """
        return db.query(Report).filter(Report.query_id == query_id).all()
    
    @staticmethod
    def get_risk_analysis_report(db: Session, query_id: int) -> Optional[Report]:
        """
        Get risk analysis report for a query
        
        Args:
            db: Database session
            query_id: Query ID
            
        Returns:
            Report: Risk analysis report or None
        """
        return (
            db.query(Report)
            .filter(Report.query_id == query_id, Report.report_type == "risk_analysis")
            .first()
        )
    
    @staticmethod
    def get_action_plan_report(db: Session, query_id: int) -> Optional[Report]:
        """
        Get action plan report for a query
        
        Args:
            db: Database session
            query_id: Query ID
            
        Returns:
            Report: Action plan report or None
        """
        return (
            db.query(Report)
            .filter(Report.query_id == query_id, Report.report_type == "action_plan")
            .first()
        )
    
    @staticmethod
    def format_risk_analysis_response(report: Report) -> RiskAnalysisResponse:
        """
        Format risk analysis report for frontend consumption
        
        Args:
            report: Risk analysis report
            
        Returns:
            RiskAnalysisResponse: Formatted response
        """
        json_data = report.json_report
        
        return RiskAnalysisResponse(
            query_id=report.query_id,
            report_id=report.id,
            summary=json_data.get("summary", {}),
            risks=json_data.get("risks", []),
            recommended_actions=json_data.get("recommended_monitoring_actions", []),
            top_sources=json_data.get("top_sources_used", []),
            confidence_score=report.confidence_score,
            generated_at=report.generated_at
        )
    
    @staticmethod
    def format_action_plan_response(report: Report) -> ActionPlanResponse:
        """
        Format action plan report for frontend consumption
        
        Args:
            report: Action plan report
            
        Returns:
            ActionPlanResponse: Formatted response
        """
        json_data = report.json_report
        
        return ActionPlanResponse(
            query_id=report.query_id,
            report_id=report.id,
            summary=json_data.get("summary", {}),
            prioritized_actions=json_data.get("prioritized_actions", []),
            confidence_score=report.confidence_score,
            generated_at=report.generated_at
        )
